### PR TITLE
Added pagination options

### PR DESCRIPTION
**Pull request by libinthomas33**
Add pagination options

[Issue](https://github.com/slavabobik/greenleaf/issues/6)

### CODE REVIEW

**Comment by slavabobik** [comment]
Thank you for contributing, but I'm apologise, I've been already working on it. If you interesting in contributing please ask first about picking an issue, it could save time and avoid miscommunication

**Comment by libinthomas-kv** [comment]
Is there any issue I can pick?

**Comment by libinthomas33** [comment]
Is there any task I can pick?

**Comment by slavabobik** [comment]
@libinthomas33 At this time no

**Pull request closed without merging**
